[project]
name = "gcli"
version = "0.1.0"
description = "gcli"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "descope>=1.7.9",
    "pygithub>=2.8.1",
    "setuptools>=80.9.0",
]
